"""Add abstract base class and restructure models

Revision ID: 386e5d807300
Revises: f2d07206cf88
Create Date: 2025-05-21 14:51:49.993847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386e5d807300'
down_revision = 'f2d07206cf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=True))
    op.add_column('donation', sa.Column('invested_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'invested_amount')
    op.drop_column('charityproject', 'invested_amount')
    # ### end Alembic commands ###
