"""Fix relationship donation-project

Revision ID: 43987d41f28a
Revises: 386e5d807300
Create Date: 2025-05-22 16:37:08.093234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43987d41f28a'
down_revision = '386e5d807300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('donation', schema=None) as batch_op:
    #     batch_op.add_column('donation', sa.Column('charity_project_id', sa.Integer(), nullable=True))
    #     batch_op.create_foreign_key(
    #         #None, 'donation', 'charityproject', ['charity_project_id'], ['id'])
    #         'fk_donation_charity_project',
    #         'charityproject',
    #         ['charity_project_id'],
    #         ['id']
    #     )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_donation_charity_project_id',
            'charityproject',
            ['charity_project_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('donation', schema=None) as batch_op:
    #     batch_op.drop_constraint(
    #         #None, 'donation', type_='foreignkey')
    #         'fk_donation_charity_project', type_='foreignkey'
    #     )
    #     batch_op.drop_column(
    #         #'donation', 'charity_project_id')
    #         'charity_project_id'
    #     )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_charity_project_id', type_='foreignkey')
        batch_op.drop_column('charity_project_id')
        # ### end Alembic commands ###
